	CacheDir=""
	MaxCacheSize=107374182400
	MaxCacheRate=0.95
	Threshold=0.8
	FreqWeight=0.3
	ServerIp=""
	ServerPort="8080"
	TokenKey=""
	AccountSeed="lunar talent spend shield blade when dumb toilet drastic unique taxi water"
	AccountID="cXgZo3RuYkAGhhvCHjAcc9FU13CG44oy8xW6jN39UYvbBaJx5"
	RpcAddr="wss://devnet-rpc.cess.cloud/ws/"
	BytePrice=1000