	CacheDir=""
	MaxCacheRate=""
	Threshold=""
	FreqWeight=""
	ServerIp="172.16.2.35"
	ServerPort="8080"
	TokenKey=""
	AccountSeed="lunar talent spend shield blade when dumb toilet drastic unique taxi water"
	AccountID="cXgZo3RuYkAGhhvCHjAcc9FU13CG44oy8xW6jN39UYvbBaJx5"
	RpcAddr="wss://testnet-rpc0.cess.cloud/ws/"
	BytePrice=1000